---
title: "sacc_角度计算"
output: html_document
date: "2023-10-10"
---
计算眼跳两点连线与水平线的夹角。

加载包
```{r}
library(tidyverse)
library(data.table)
library(furrr)
```

定义计算方法
```{r}
calculate_saccade_angle <- function(input_file_path, output_file_path) {
  # 读取输入文件中的数据
  dt <- fread(input_file_path)

  # 定义函数calculate_angle，该函数计算两点之间的线段的角度
  calculate_angle <- function(x1, y1, x2, y2) {
    # 计算x和y的差值
    delta_x <- x2 - x1
    delta_y <- y2 - y1

    # 使用atan2函数计算角度，并将其转换为度数
    angle <- atan2(delta_y, delta_x) * (180 / pi)

    # 根据x和y的差值的正负，对角度进行调整
    angle[delta_x > 0 & delta_y < 0] <- atan2(-delta_y[delta_x > 0 & delta_y < 0], delta_x[delta_x > 0 & delta_y < 0]) * (180 / pi)
    angle[delta_x > 0 & delta_y > 0] <- 360 - atan2(delta_y[delta_x > 0 & delta_y > 0], delta_x[delta_x > 0 & delta_y > 0]) * (180 / pi)
    angle[delta_x < 0 & delta_y < 0] <- 180 - atan2(abs(delta_y[delta_x < 0 & delta_y < 0]), abs(delta_x[delta_x < 0 & delta_y < 0])) * (180 / pi)
    angle[delta_x < 0 & delta_y > 0] <- 270 - atan2(delta_y[delta_x < 0 & delta_y > 0], -delta_x[delta_x < 0 & delta_y > 0]) * (180 / pi)
    angle[delta_x == 0 & delta_y > 0] <- 270
    angle[delta_x == 0 & delta_y < 0] <- 90
    angle[delta_x > 0 & delta_y == 0] <- 0
    angle[delta_x < 0 & delta_y == 0] <- 180

    # 返回计算得到的角度
    return(angle)
  }

  # 使用mutate函数，为dt添加一列angle，该列的值由calculate_angle函数计算得到
  dt <- dt %>% mutate(angle = calculate_angle(sxp, syp, exp, eyp))

  # 将处理后的数据保存到输出文件路径中
  fwrite(dt, output_file_path, na = "NA")
}


# 定义函数batch_calculate_saccade_angle，该函数对指定目录下的全部文件进行批量处理，
# 并将处理结果输出到指定的目录下。该函数接收两个参数：输入文件的目录和工作线程的数量。
batch_calculate_saccade_angle <- function(input_dir, wk = 5) {
  # 获取输入目录下的全部文件的路径
  input_file_paths <- list.files(input_dir, full.names = TRUE)

  # 设置并行计划，使用多个会话进行并行计算
  plan(multisession, workers = wk)

  # 对输入目录下的全部文件进行批量处理，并将处理结果输出到指定的目录下
  future_map2(input_file_paths, input_file_paths, calculate_saccade_angle)

  # 重置并行计划为顺序计划
  plan(sequential)
}
```

调用方法，批量计算
```{r}
# 输入目录
input_dir <- "../yajuan_data/out/sacc2_AOI"

# 调用方法
batch_calculate_saccade_angle(input_dir)
```