---
title: "yandong"
author: "yj"
date: "`r Sys.Date()`"
output: html_document
---
1#安装eyelinker包
```{r}
install.packages("tidyverse")
install.packages("eyelinker")
library(eyelinker)
library(archive)
```

2#读取asc文件
```{r}
a1<- read_asc("E:/data/edf/A001.asc")
View(a1)  
```
3#导出单个人的数据
```{r}
f1<- a1$raw
write.csv(f1, "f1.csv")
write.csv(f1,archive_write("f1.zip","f1.csv"))
f2 <- a1$sacc
write.csv(f2, file = "f2.csv")
f3 <- a1$fix
write.csv(f3, file = "f3.csv")
f4 <- a1$blinks
write.csv(f4, file = "f4.csv")
f5 <- a1$msg
write.csv(f5, file = "f5.csv")
write.csv(f4, file = "f4.csv")
f6 <- a1$info
write.csv(f6, file = "f6.csv")
```
4#用for函数批量导出所有人的数据
```{r}
library(tidyverse)
library(archive)
library(eyelinker)
setwd('E:/data/edf')
files<-list.files(path = ".",pattern = '.asc')
length(files)
for (i in 1:length(files)){
  dat<- read_asc(files[i])
  f1<- dat$raw
  write.csv(f1, file = paste(files[i],"f1.csv",sep='_'))
  f2 <- dat$sacc
  write.csv(f2, file = paste(files[i],"f2.csv",sep='_'))
  f3 <- dat$fix
  write.csv(f3, file = paste(files[i],"f3.csv",sep='_'))
  f4 <- dat$blinks
  write.csv(f4, file = paste(files[i],"f4.csv",sep='_'))
  f5 <- dat$msg
  write.csv(f5, file = paste(files[i],"f5.csv",sep='_'))
  f6 <- dat$info
  write.csv(f6, file = paste(files[i],"f6.csv",sep='_'))
}
```
加载包
```{r}
library(tidyverse)
library(eyelinker)
```
尝试批量处理
```{r}
# 定义一个函数“read_raw”，功能是从asc文件中提取输出raw文件
read_raw <- function(a, dir){
  b <- read_asc(a)
  c <- b$raw
  c <- mutate(c, participants=basename(a))
  write_csv(c, paste(dir,".csv", sep = ""))
}

# 定义一个函数“read_sacc”，功能是从asc文件中提取输出sacc文件
read_sacc <- function(a, dir){
  b <- read_asc(a)
  c <- b$sacc
  c <- mutate(c, participants=basename(a))
  write_csv(c, paste(dir,".csv", sep = ""))
}
# 定义一个函数“read_fix”，功能是从asc文件中提取输出fix文件
read_fix <- function(a, dir){
  b <- read_asc(a)
  c <- b$fix
  c <- mutate(c, participants=basename(a))
  write_csv(c, paste(dir,".csv", sep = ""))
}
# 定义一个函数“read_blinks”，功能是从asc文件中提取输出blinks文件
read_blinks <- function(a, dir){
  b <- read_asc(a)
  c <- b$blinks
  c <- mutate(c, participants=basename(a))
  write_csv(c, paste(dir,".csv", sep = ""))
}
# 定义一个函数“read_msg”，功能是从asc文件中提取输出msg文件
read_msg <- function(a, dir){
  b <- read_asc(a)
  c <- b$msg
  c <- mutate(c, participants=basename(a))
  write_csv(c, paste(dir,".csv", sep = ""))
}
# 定义一个函数“read_info”，功能是从asc文件中提取输出nifo文件
read_info <- function(a, dir){
  b <- read_asc(a)
  c <- b$info
  c <- mutate(c, participants=basename(a))
  write_csv(c, paste(dir,".csv", sep = ""))
}
#获取asc文件列表
file_list <- list.files("dd/asc/")

#把asc文件列表变成路径列表
nlist <- str_c("dd/asc/", file_list)

#做一个raw输出的路径列表
n2list <- str_c("dd/raw/", file_list)

#做一个sacc输出的路径列表
n3list <- str_c("dd/sacc/", file_list)
#做一个fix输出的路径列表
n4list <- str_c("dd/fix/", file_list)
#做一个blinks输出的路径列表
n5list <- str_c("dd/blinks/", file_list)
#做一个msg输出的路径列表
n6list <- str_c("dd/msg/", file_list)
#做一个info输出的路径列表
n7list <- str_c("dd/info/", file_list)
#建立相应文件夹
dir.create("dd/raw/")
dir.create("dd/sacc/")
dir.create("dd/fix/")
dir.create("dd/blinks/")
dir.create("dd/msg/")
dir.create("dd/info/")
#运用map2函数批量处理数据
map2(nlist, n2list, read_raw)
map2(nlist, n3list, read_sacc)
map2(nlist, n4list, read_fix)
map2(nlist, n5list, read_blinks)
map2(nlist, n6list, read_msg)
map2(nlist, n7list, read_info)


```