---
title: "p2"
output: html_document
date: "2023-06-28"
---

加载包
```{r}
library(tidyverse)
library(readxl)
```


```{r}

msg_list <- list.files("/Users/placenameday/Downloads/msg/", full.names = T)
msg <- read_csv(msg_list)

stim_info <- function(path, path2){
  data <- read_csv(path)
  
  par <- str_sub(path, start = -12L, end = -5L)
  
  msg <- msg %>% filter(participants==par)
  
  f1 <- function(a,b,c,d){
    mutate(data, stim=if_else(between(stime, a, b) & between(etime, a, b), c,NA), pic=if_else(between(stime, a, b) & between(etime, a, b), d, NA)) %>%
      drop_na()
  }

  a <- pmap(list(msg$Stime, msg$Etime, msg$stim, msg$pic), f1) %>% bind_rows()
  
  write_csv(a, path2)
  gc()
}

#获取文件列表
file_list <- list.files("/Users/placenameday/Downloads/blink")

#输入路径列表
blink_list <- str_c("/Users/placenameday/Downloads/blink/", file_list)

#输出路径
blink_list2 <- str_c("/Users/placenameday/Downloads/blink2/", file_list)

#建立输出文件夹
dir.create("/Users/placenameday/Downloads/blink2")

map2(blink_list, blink_list2, stim_info)
```



函数化批量处理
```{r}

```