---
title: "批量文件重命名"
output: html_document
date: "2023-06-30"
---

加载包
```{r}
library(tidyverse)
library(readxl)
```


```{r}
myfilepath <- "/Users/placenameday/R study/yajuan_data/out/blinks2"

setwd(myfilepath)

alltypefiles <- dir(myfilepath)

newname <- gsub(pattern = ".sacc", replacement = ".blink", x = alltypefiles)

file.rename(alltypefiles, newname)



myfilepath <- "/Users/placenameday/R study/yajuan_data/out/fix2"

setwd(myfilepath)

alltypefiles <- dir(myfilepath)

newname <- gsub(pattern = ".asc", replacement = ".fix", x = alltypefiles)

file.rename(alltypefiles, newname)



myfilepath <- "/Users/placenameday/R study/yajuan_data/out/sacc2"

setwd(myfilepath)

alltypefiles <- dir(myfilepath)

newname <- gsub(pattern = ".asc", replacement = ".sacc", x = alltypefiles)

file.rename(alltypefiles, newname)


myfilepath <- "/Users/placenameday/R study/yajuan_data/out/raw2"

setwd(myfilepath)

alltypefiles <- dir(myfilepath)

newname <- gsub(pattern = ".asc", replacement = ".raw", x = alltypefiles)

file.rename(alltypefiles, newname)
```

