---
title: "AOI"
output: html_document
date: "2023-08-17"
---
摘要：标注fixation数据的AOI

加载包
```{r} 
library(tidyverse)
library(readxl)
library(furrr)
library(data.table)
```

读取AOI信息
```{r, echo=FALSE, message=FALSE}
# 定义函数aoi_cacu1，该函数在特定的 pic 和 area 下，根据 fix 数据的坐标信息返回打标判断
aoi_cacu1 <- function(x, a, b) {
  # 筛选出 area 等于 x 的行
  aoi1 <- a %>% filter(area == x)

  # 根据 axp 和 ayp 的值是否在 aoi1 的 X1、X2、Y1、Y3 的范围内，添加新的列 x
  fixation2 <- b %>%
    mutate(!!x := case_when(between(axp, aoi1$X1, aoi1$X2) & between(ayp, aoi1$Y1, aoi1$Y3) ~ 1,
      .default = 0
    ))
}

# 定义函数aoi_cacu2，该函数在特定的 pic 下遍历全部的 area 值，并利用 aoi_cacu1 进行打标
aoi_cacu2 <- function(x, a, f) {
  # 筛选出 pic 等于 x 的行
  ta <- a %>% filter(pic == x)

  # 筛选出 pic 等于 x 的行
  tf <- f %>% filter(pic == x)

  # 对 ta 的 area 列的每个值，使用 aoi_cacu1 函数进行处理，然后将结果进行合并
  tt2 <- reduce(future_map(ta$area, ~ aoi_cacu1(.x, ta, tf)), full_join)
}

# 定义函数aoi_cacu3，该函数将特定目录下的数据文件批量打标并输出
aoi_cacu3 <- function(x, y) {
  # 读取数据文件
  data <- fread(x)

  # 读取 AOI 坐标信息，将坐标部分数据转换为数字格式
  aoi <- read_excel("info/area2.xlsx") %>%
    mutate_at(vars(3:6), as.numeric)

  # 提取 data 和 aoi 中 pic 列的交集
  piclist <- intersect(unique(data$pic), unique(aoi$pic))

  # 根据 piclist，筛选出 data 和 aoi 中 pic 列的值在 piclist 中的行
  data_t <- data %>% filter(pic %in% piclist)
  aoi_t <- aoi %>% filter(pic %in% piclist)

  # 对 piclist 的每个值，使用 aoi_cacu2 函数进行处理，然后将结果进行合并
  fixation2 <- future_map(piclist, ~ aoi_cacu2(.x, aoi_t, data_t)) %>% bind_rows()

  # 将结果保存到输出文件路径中
  fwrite(fixation2, paste0(y, ".aoi.csv"), na = "NA")
}

# 定义函数aoi_cacu5，该函数接收一个目录路径，然后在该目录的上级目录中创建一个新目录，
# 新目录的名称为原目录名称+"_AOI"。然后，该函数会获取原目录下的所有文件的列表，
# 并生成新目录下的对应文件的列表。最后，该函数会批量处理原目录下的所有文件，
# 并将处理结果保存到新目录下的对应文件中。
aoi_cacu5 <- function(x) {
  # 获取原目录下的所有文件的列表
  filelist <- list.files(x, full.names = TRUE)

  # 获取原目录的名称
  dirname <- basename(x)

  # 获取原目录的上级目录的路径
  parentdir <- dirname(x)

  # 在原目录的上级目录中创建新目录
  dir.create(paste0(parentdir, "/", dirname, "_AOI"))

  # 生成新目录下的对应文件的列表
  filelist2 <- paste0(parentdir, "/", dirname, "_AOI/", basename(filelist))

  # 批量处理原目录下的所有文件，并将处理结果保存到新目录下的对应文件中
  future_map2(filelist, filelist2, aoi_cacu3)
}
```

批量处理数据
```{r, echo=FALSE, message=FALSE}
# 设置多线程处理
plan(multisession, workers = 6)
# 批量处理数据
aoi_cacu5("../yajuan_data/out/fix2")
# 恢复单线程处理
plan(sequential)
```
