---
title: "AOI_yuliao"
output: html_document
date: "2023-11-21"
---
摘要：标注fixation数据的语料属性AOI

加载包
```{r} 
library(tidyverse)
library(readxl)
library(furrr)
library(data.table)
```

读取AOI信息
```{r, echo=FALSE, message=FALSE}
calculate_fix_AOI2 <- function(input_file_path, output_file_path) {
  # 从 "info/area3_2.csv" 文件中读取 AOI 数据
  aoi <- read_csv("info/area3_2.csv")

  # 读取输入文件，并添加行号
  dt <- fread(input_file_path) %>%
    mutate(RowNumber = row_number()) # 添加行号

  # 将dt和aoi进行左连接，并计算AOI
  result <- dt %>%
    left_join(aoi, by = "pic", relationship = "many-to-many") %>% # 根据"pic"列进行左连接
    mutate(
      AOI = ifelse(
        axp >= X1 & ayp >= Y1 & axp <= X2 & ayp <= Y3, # 判断axp和ayp是否在指定的范围内
        area, # 如果在范围内，AOI的值为"area"
        NA # 如果不在范围内，AOI的值为NA
      )
    )

  # 从结果中选择除了 'area', 'X1', 'X2', 'Y1', 'Y3' 这几列之外的所有列
  # 使用 unique() 函数去除重复行
  r1 <- result %>%
    select(-area, -X1, -X2, -Y1, -Y3) %>%
    unique()

  # 使用dplyr筛选数据框
  # 对r1进行分组，分组依据是block, pic, RowNumber
  dt_r1 <- r1 %>%
    group_by(block, pic, RowNumber) %>%
    # 对每个分组进行汇总
    # 如果AOI列全是NA，那么结果就是NA
    # 否则，结果是AOI列中的第一个非NA值
    summarize(AOI = ifelse(all(is.na(AOI)), NA, first(na.omit(AOI))))

  # 将 dt_r1 和 dt 进行左连接
  new_dt <- dt_r1 %>%
    left_join(dt) %>%
    # 添加新的 AOI 列
    # 如果 AOI 列的值是 NA，并且 axp 和 ayp 的值在指定的范围内，那么 AOI 的值就是 "BG"
    # 否则，AOI 的值就是原来的值
    mutate(
      AOI = if_else(is.na(AOI) & (between(axp, 0, 1280) & between(ayp, 0, 1024)), "BG", AOI)
    )

  # 将new_dt中的AOI列的字符中，所有"_"以及之后的数字删掉
  new_dt$AOI <- str_remove(new_dt$AOI, "_\\d+")

  # 将结果保存到输出文件路径中
  fwrite(new_dt, output_file_path, na = "NA")
}

# 对特定目录下的全部文件批量处理，并输出到指定目录下
batch_fix_AOI2 <- function(input_dir, output_dir, wk = 5) {
  # 获取输入目录下的所有文件路径
  input_file_paths <- list.files(input_dir, full.names = TRUE)
  # 将输入文件路径替换为输出文件路径
  output_file_paths <- str_replace(input_file_paths, input_dir, output_dir)
  # 设置并行计划，使用多个会话进行并行计算
  plan(multisession, workers = wk)
  # 对每对输入文件路径和输出文件路径，使用 calculate_fix_AOI2 函数进行计算
  future_map2(input_file_paths, output_file_paths, calculate_fix_AOI2)
  # 设置并行计划为顺序计划，即不进行并行计算
  plan(sequential)
}
```

调用方法，批量计算
```{r}
# 输入目录
input_dir <- "../yajuan_data/out/fix2"
# 输出目录
output_dir <- "../yajuan_data/out/fix2_AOI_yuliao"
# 建立输出目录
dir.create(output_dir, recursive = TRUE)
# 调用方法
batch_fix_AOI2(input_dir, output_dir)
```
