---
title: "眼跳AOI语料属性打标"
output: html_document
date: "2023-08-17"
---
摘要：标注saccade数据的语料属性AOI，改变打标方式，增加BG区域的判断方法

加载包
```{r} 
library(tidyverse)
library(readxl)
library(furrr)
library(data.table)
```

定义计算方法
```{r}
calculate_saccade_angle <- function(input_file_path, output_file_path) {
  # 从 "info/area3_2.csv" 文件中读取 AOI 数据，并将第3列到第6列的数据类型转换为数值型
  aoi <- read_csv("info/area3_2.csv") %>%
    mutate_at(vars(3:6), as.numeric)

  # 读取输入文件，并添加行号
  dt <- fread(input_file_file_path) %>%
    mutate(RowNumber = row_number())

  # 将dt和aoi进行左连接，并计算AOI_S和AOI_E
  result <- dt %>%
    left_join(aoi, by = "pic", relationship = "many-to-many") %>%
    mutate(
      AOI_S = ifelse(
        sxp >= X1 & syp >= Y1 & sxp <= X2 & syp <= Y3,
        area, NA
      ),
      AOI_E = ifelse(
        exp >= X1 & eyp >= Y1 & exp <= X2 & eyp <= Y3,
        area, NA
      )
    )

  # 从结果中选择除了 'AOI_E', 'area', 'X1', 'X2', 'Y1', 'Y3' 这几列之外的所有列，并去除重复行
  r1 <- result %>%
    select(-AOI_E, -area, -X1, -X2, -Y1, -Y3) %>%
    unique()

  # 从结果中选择除了 'AOI_S', 'area', 'X1', 'X2', 'Y1', 'Y3' 这几列之外的所有列，并去除重复行
  r2 <- result %>%
    select(-AOI_S, -area, -X1, -X2, -Y1, -Y3) %>%
    unique()

  # 对r1进行分组，分组依据是block, pic, RowNumber
  # 对每个分组进行汇总
  # 如果 AOI_S 列全是 NA，那么结果就是 NA
  # 否则，结果是 AOI_S 列中的第一个非 NA 值
  dt_r1 <- r1 %>%
    group_by(block, pic, RowNumber) %>%
    summarize(AOI_S = ifelse(all(is.na(AOI_S)), NA, first(na.omit(AOI_S))))

  # 对r2进行分组，分组依据是block, pic, RowNumber
  # 对每个分组进行汇总
  # 如果 AOI_E 列全是 NA，那么结果就是 NA
  # 否则，结果是 AOI_E 列中的第一个非 NA 值
  dt_r2 <- r2 %>%
    group_by(block, pic, RowNumber) %>%
    summarize(AOI_E = ifelse(all(is.na(AOI_E)), NA, first(na.omit(AOI_E))))

  # 将 dt_r1 和 dt_r2 进行全连接，然后与 dt 进行左连接
  # 如果 AOI_S 列的值是 NA，并且 sxp 和 syp 的值在指定的范围内，那么 AOI_S 的值就是 "BG"
  # 如果 AOI_E 列的值是 NA，并且 exp 和 eyp 的值在指定的范围内，那么 AOI_E 的值就是 "BG"
  new_dt <- full_join(dt_r1, dt_r2) %>%
    left_join(dt) %>%
    mutate(
      AOI_S = if_else(is.na(AOI_S) & (between(sxp, 0, 1280) & between(syp, 0, 1024)), "BG", AOI_S),
      AOI_E = if_else(is.na(AOI_E) & (between(exp, 0, 1280) & between(eyp, 0, 1024)), "BG", AOI_E)
    )

  # 将new_dt中的AOI_S和AOI_E列的字符中，所有"_"以及之后的数字删掉
  new_dt$AOI_S <- str_remove(new_dt$AOI_S, "_\\d+")
  new_dt$AOI_E <- str_remove(new_dt$AOI_E, "_\\d+")

  # 将结果保存到输出文件路径中
  fwrite(new_dt, output_file_path, na = "NA")
}

# 对特定目录下的全部文件批量处理，并输出到指定目录下
batch_calculate_saccade_angle <- function(input_dir, output_dir, wk = 5) {
  input_file_paths <- list.files(input_dir, full.names = TRUE)
  output_file_paths <- str_replace(input_file_paths, input_dir, output_dir)
  plan(multisession, workers = wk)
  future_map2(input_file_paths, output_file_paths, calculate_saccade_angle)
  plan(sequential)
}
```

调用方法，批量计算
```{r}
# 输入目录
input_dir <- "../yajuan_data/out/sacc2"
# 输出目录
output_dir <- "../yajuan_data/out/sacc2_AOI_yuliao"
# 建立输出目录
dir.create(output_dir, recursive = TRUE)
# 调用方法
batch_calculate_saccade_angle(input_dir, output_dir)
```
