---
title: "AOI"
output: html_document
date: "2023-08-17"
---
摘要：标注saccade数据的AOI，改变打标方式，增加BG区域的判断方法

加载包
```{r} 
library(tidyverse)
library(readxl)
library(furrr)
library(data.table)
```

读取AOI信息
```{r, echo=FALSE, message=FALSE, warning=FALSE}
# 定义函数ac1, 在特定pic下与特定area下，根据sacc数据坐标信息返回打标判断
aoi_cacu1 <- function(x, a, b) {
  aoi1 <- a[area == x]

  b[, `:=`(AOI_S = NULL, AOI_E = NULL)]

  b[between(sxp, aoi1$X1, aoi1$X2) & between(syp, aoi1$Y1, aoi1$Y3), AOI_S := x]
  b[between(exp, aoi1$X1, aoi1$X2) & between(eyp, aoi1$Y1, aoi1$Y3), AOI_E := x]

  return(b)
}

# 定义函数ac2, 在特定pic下遍历全部area值，并利用ac1进行打标
aoi_cacu2 <- function(x, a, f) {
  ta <- a %>% filter(pic == x)

  tf <- f %>% filter(pic == x)

  tt2 <- future_pmap_dfr(ta$area, ~ aoi_cacu1(.x, ta, tf))
}

# 定义函数ac3，将特定目录下的数据文件批量打标并输出，每行增加注释
aoi_cacu3 <- function(x, y) {
  # 读取数据文件
  data <- fread(x)

  # 读取AOI坐标信息，将坐标部分数据转换为数字格式
  aoi <- readxl::read_excel("info/area2.xlsx") %>%
    as.data.table() %>%
    setnames(c("pic", "area", "X1", "Y1", "X2", "Y3")) %>%
    setcolorder(c("pic", "area", "X1", "X2", "Y1", "Y3")) %>%
    as.data.frame() %>%
    mutate_at(vars(3:6), as.numeric) %>%
    as.data.table()

  # 提取数据文件与AOI信息文件中刺激物的交集列表
  piclist <- intersect(unique(data$pic), unique(aoi$pic))

  # 根据交集列表剔除数据文件与AOI信息中无法打标的数据
  data_t <- data[pic %in% piclist]
  aoi_t <- aoi[pic %in% piclist]

  # 处理当前数据，打标AOI信息
  fixation2 <- future_map(piclist, ~ aoi_cacu2(.x, aoi_t, data_t)) %>% bind_rows()

  # 增加bg区域的判断
  fixation2[, AOI_S := ifelse(is.na(AOI_S) & between(sxp, 0, 1280) & between(syp, 0, 1024), "BG", AOI_S)]
  fixation2[, AOI_E := ifelse(is.na(AOI_E) & between(exp, 0, 1280) & between(eyp, 0, 1024), "BG", AOI_E)]

  # 输出数据
  fwrite(fixation2, paste0(y, ".aoi.csv"), na = "NA")
}

# 定义函数ac5，接收一个目录A，并在A目录的上级目录新建一个目录B，名称为A的上级+"_AOI"。生成A目录下的文建列表，同时结合A的文件名与B目录，生成B目录下的文件列表。批量处理A目录下的文件，将处理结果输出到B目录下的文件列表。
aoi_cacu5 <- function(x) {
  # 获取目录下的文件列表
  filelist <- list.files(x, full.names = TRUE)
  # 获取目录名
  dirname <- basename(x)
  # 获取上级目录名
  parentdir <- dirname(x)
  # 新建目录
  dir.create(paste0(parentdir, "/", dirname, "_AOI2"))
  # 生成新目录下的文件列表
  filelist2 <- paste0(parentdir, "/", dirname, "_AOI2/", basename(filelist))
  # 批量处理文件
  future_map2(filelist, filelist2, aoi_cacu3)
}
```

批量处理数据
```{r, echo=FALSE, message=FALSE}
# 设置多线程处理
plan(multisession, workers = 6)
# 批量处理数据
aoi_cacu5("../yajuan_data/out/sacc2")
# 恢复单线程处理
plan(sequential)
```
