---
title: "AOI_yuliao_raw"
output: html_document
date: "2023-11-21"
---
摘要：标注raw数据的语料属性AOI

加载包
```{r} 
library(tidyverse)
library(readxl)
library(furrr)
library(data.table)
```

读取AOI信息
```{r, echo=FALSE, message=FALSE}
calculate_raw_AOI2 <- function(input_file_path, output_file_path) {
  # 从 "info/area3_2.csv" 文件中读取 AOI 数据
  aoi <- read_csv("info/area3_2.csv")

  # 读取输入文件，并添加行号
  dt <- fread(input_file_path) %>%
    mutate(RowNumber = row_number()) # 为数据框添加行号列

  # 根据dt是否包含"xpl"列，将"x_val"和"y_val"两列的值设置为dt中的"xpl"和"ypl"列或"xp"和"yp"列的数值
  dt[, c("x_val", "y_val") := .(
    if ("xpl" %in% names(dt)) get("xpl") else get("xp"),
    if ("xpl" %in% names(dt)) get("ypl") else get("yp")
  )]

  # 将dt和aoi进行左连接，并计算AOI
  result <- dt %>%
    left_join(aoi, by = "pic", relationship = "many-to-many") # 根据"pic"列将dt和aoi进行左连接

  # 将 result 转换为 data.table 对象
  result <- data.table(result)

  # 如果 x_val 和 y_val 的值在指定的范围内，那么 AOI 的值就是 "area"，否则，AOI 的值就是 NA
  result[, AOI := ifelse(x_val >= X1 & y_val >= Y1 & x_val <= X2 & y_val <= Y3, area, NA)]

  # 从结果中选择除了 'area', 'X1', 'X2', 'Y1', 'Y3' 这几列之外的所有列，并去除重复行
  r1 <- result %>%
    select(-area, -X1, -X2, -Y1, -Y3) %>%
    unique()

  # 对r1进行分组，分组依据是block, pic, RowNumber
  # 对每个分组进行汇总
  # 如果 AOI 列全是 NA，那么结果就是 NA
  # 否则，结果是 AOI 列中的第一个非 NA 值
  r1[, AOI := ifelse(all(is.na(AOI)), NA, AOI[!is.na(AOI)][1]), by = .(block, pic, RowNumber)]

  # 将 r1 和 dt 进行左连接
  new_dt <- r1 %>%
    left_join(dt)

  # 如果 AOI 列的值是 NA，并且 x_val 和 y_val 的值在指定的范围内，那么 AOI 的值就是 "BG"
  # 否则，AOI 的值就是原来的值
  new_dt[, AOI := ifelse(is.na(AOI) & x_val >= 0 & x_val <= 1280 & y_val >= 0 & y_val <= 1024, "BG", AOI)]

  # 删除 x_val 和 y_val 列
  new_dt[, c("x_val", "y_val") := NULL]

  # 使用 := 操作符替换 AOI 列的值
  # 将 AOI 列的字符中，所有 "_" 以及之后的数字删掉
  new_dt[, AOI := sub("_\\d+", "", AOI)]

  # 使用 unique() 函数去除 new_dt 中的重复行
  new_dt <- unique(new_dt)

  # 将结果保存到输出文件路径中
  fwrite(new_dt, output_file_path, na = "NA")
}

# 对特定目录下的全部文件批量处理，并输出到指定目录下
batch_raw_AOI2 <- function(input_dir, output_dir, wk = 5) {
  # 获取输入目录下的所有文件路径
  input_file_paths <- list.files(input_dir, full.names = TRUE)
  # 将输入文件路径替换为输出文件路径
  output_file_paths <- str_replace(input_file_paths, input_dir, output_dir)
  # 设置并行计划，使用多个会话进行并行计算
  plan(multisession, workers = wk)
  # 对每对输入文件路径和输出文件路径，使用 calculate_raw_AOI2 函数进行计算
  future_map2(input_file_paths, output_file_paths, calculate_raw_AOI2)
  # 设置并行计划为顺序计划，即不进行并行计算
  plan(sequential)
}
```

调用方法，批量计算
```{r}
# 输入目录
input_dir <- "../yajuan_data/out/raw2"
# 输出目录
output_dir <- "../yajuan_data/out/raw2_AOI_yuliao"
# 建立输出目录
dir.create(output_dir, recursive = TRUE)
# 调用方法
batch_raw_AOI2(input_dir, output_dir)
```
