---
title: "数据清洗"
output: html_document
date: "2023-09-05"
---
摘要：通过计算眼动采样率的丢失率，对眼动数据进行清洗

加载包
```{r} 
library(tidyverse)
library(readxl)
library(furrr)
library(data.table)
```

定义丢失率函数，适用于raw文件中包含单眼数据与双眼数据的情况
```{r, echo=FALSE, message=FALSE}
# 读取raw数据文件
dt <- fread("/Users/placenameday/R study/yajuan_data/out/raw/A002.asc.csv")

# 定义丢失率函数，适用于raw文件中包含双眼数据的情况
track_loss_rate_bin <- function(dt) {
    # 读取dt,新建一列数据“track_loss”,判断xpl,ypl为一组，xpr,ypr为一组，若其中两组中都包含NA，则为丢失数据，标记为1，否则为0
    dt2 <- dt %>% mutate(track_loss = ifelse((is.na(xpl) | is.na(ypl)) & (is.na(xpr) | is.na(ypr)), 1, 0))
    
    # 计算丢失率，即track_loss列的均值
    track_loss_rate_block <- dt2 %>% group_by(block) %>% summarise(track_loss_rate_block = mean(track_loss)) %>%
        mutate(track_loss_rate_all = mean(dt2$track_loss))
    
    # 返回丢失率信息
    return(track_loss_rate_block)
}

# 定义丢失率函数，适用于raw文件中包含单眼数据的情况
track_loss_rate_bin_mono <- function(dt) {
    # 读取dt,新建一列数据“track_loss”,判断xp与yp中包含任意NA，则为丢失数据，标记为1，否则为0
    dt2 <- dt %>% mutate(track_loss = ifelse((is.na(xp) | is.na(yp)), 1, 0))
    
    # 计算丢失率，即track_loss列的均值
    track_loss_rate_block <- dt2 %>% group_by(block) %>% summarise(track_loss_rate_block = mean(track_loss)) %>%
        mutate(track_loss_rate_all = mean(dt2$track_loss))
    
    # 返回丢失率信息
    return(track_loss_rate_block)
}
```



