---
output:
  word_document: default
  html_document: default
  pdf_document: default
---
加载包
```{r} 
library(tidyverse)
library(readxl)
library(data.table)
library(furrr)
library(ggpubr)
library(rstatix)
library(datarium)
library(emmeans)
library(dplyr)
library(reshape)
```

定义方法
```{r, echo=FALSE, message=FALSE}
# 筛选phn

  fix_info <- read_csv("../yajuan_data/statics/fixation/fixation_01.csv")
   ph <- read_xlsx("C:/Users/86180/Desktop/sch.xlsx")
   ph1<- left_join(ph,fix_info)
   ciji <- filter(ph1,type == "sch",AOI == "yuduan")
  
  # 筛选中性
 
  fix_info_baseline <-read_csv("../yajuan_data/statics/fixation/fixation_01_baseline.csv")
  phnab <- read_xlsx("C:/Users/86180/Desktop/sch.xlsx")
  phnb<- left_join(phnab,fix_info_baseline )
  zx <- filter(phnb,type == "sch",baseline_type=="neutral",AOI == "yuduan")
  zx <- zx[,!(names(zx) %in% "type")] %>% rename(c("baseline_type"="type"))
 
  # 筛选负性
  
  fix_info_baseline <-read_csv("../yajuan_data/statics/fixation/fixation_01_baseline.csv")
  phnab <- read_xlsx("C:/Users/86180/Desktop/sch.xlsx")
  phnb<- left_join(phnab,fix_info_baseline )
  fx <- filter(phnb,type == "sch",baseline_type=="negative",AOI == "yuduan")
  fx <- fx[,!(names(fx) %in% "type")]%>% rename(c("baseline_type"="type"))
  A <-bind_rows(zx,ciji,fx )
 
 
```


```{r}
#计算均值和标准差
A %>% group_by(type, group) %>% get_summary_stats(fixation_duration, type = "mean_sd")

#可视化
bxp <- ggboxplot(A,x="type",y="fixation_duration",color="group",palette = "jco")
bxp

#极端值
A %>% group_by(type,group) %>%
 identify_outliers(fixation_duration)%>% drop()

#正态检验
model<-lm(fixation_duration~ group, data=A)
ggqqplot(residuals(model))
shapiro_test(residuals(model))
#按照组检查正态性假设
A %>% group_by(type,group) %>%  shapiro_test(fixation_duration)

#创建QQ图
ggqqplot(A, "fixation_duration", ggtheme = theme_bw()) +
  facet_grid(type ~ group)

#方差齐性检验
A %>% levene_test(fixation_duration~ type*group)

#方差分析#交互效应和主效应计算
res.avo <- A %>% anova_test(fixation_duration~ type*group)
res.avo

#计算简单主效应
model <- lm(fixation_duration~ type*group, data = A)
A %>% group_by(type) %>% anova_test(fixation_duration~ group, error = model)

#计算成对比较
pwc <- A %>% 
  group_by(type) %>%
  emmeans_test(fixation_duration~ group, p.adjust.method = "bonferroni") 
pwc
#非显著的交互作用，计算成对比较
res.avo
A %>%
  pairwise_t_test(
    fixation_duration~ group, 
    p.adjust.method = "bonferroni"
    )
model <- lm(fixation_duration~ type * group, data = A)
A %>% 
  emmeans_test(
    fixation_duration~ group, p.adjust.method = "bonferroni",
    model = model)
#报告
pwc <- pwc %>% add_xy_position(x = "type")
bxp + stat_pvalue_manual(pwc) + labs(subtitle = get_test_label(res.avo, detailed = TRUE), caption = get_pwc_label(pwc))

```



